package GUI;

import Core.*;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.HashSet;
import java.util.Observable;
import java.util.Observer;

public class Accueil implements Observer {

	private JFrame frame;
	private JButton créerUnProjetButton;
	private JList list1;
	private JPanel panel;
	private User user;
	private DefaultListModel list_data;

	public Accueil() {

		frame = new JFrame("Accueil - Dashlist");
		$$$setupUI$$$();
		frame.setIconImage(frame.getToolkit().getImage("icon2.png"));
		frame.setContentPane(panel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setLocationRelativeTo(null);
		frame.setVisible(false);

	}

	public void loadAccount(User user) {

		HashSet<Board> boards = user.getBoards();

		for (Board board : boards) {

			list_data.addElement(board.getName());
		}

		frame.revalidate();
		frame.pack();

		frame.setVisible(true);
	}

	@Override
	public void update(Observable o, Object arg) {

		String sender = o.getClass().getName();

		if (sender.equals("GUI.Login"))
			loadAccount((User) arg);
	}

	private void createUIComponents() {

		list_data = new DefaultListModel();
		list1 = new JList(list_data);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {

		createUIComponents();
		panel = new JPanel();
		panel.setLayout(new GridLayoutManager(1, 2, new Insets(10, 10, 10, 10), -1, -1));
		créerUnProjetButton = new JButton();
		créerUnProjetButton.setText("Créer un projet");
		panel.add(créerUnProjetButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
		panel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel1.setBorder(BorderFactory.createTitledBorder(null, "Mes projets", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(panel1.getFont().getName(), panel1.getFont().getStyle(), 16)));
		list1.setVisibleRowCount(8);
		list1.putClientProperty("List.isFileList", Boolean.FALSE);
		panel1.add(list1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {

		return panel;
	}
}
